version: '3.2'

services:
  share:
    build:
      context: .
      dockerfile: Dockerfile.pubkey
    ports:
      - '10022:22'
    volumes:
      - ./shared:/home/guest/shared
    command: /bin/sh -c "/etc/init.d/ssh start && tail -f /var/log/alternatives.log"
